### ISSUE TITLE
How to retrieve data which fields validation failed

### ISSUE THREAD

**Issue by venkatesulua1990** [Axway-API-Management-Plus/openapi-validator#5]
Hi
when validation fails it prints in logs like below and the same i wan to return back to Consumer in response, please let me know how to fetch that details , is that stored in any msg variable?

<html>
<body>

OpenAPIValidator: Object instance has properties which are not allowed by the schema: ["data"]
--
ERROR | 3/25/22, 11:30:11.570 | OpenAPIValidator: Object has missing required properties (["created","drugInfo","id","patient"])

</body>
</html>

**Comment by cwiechmann** [comment]
Hi @venkatesulua1990, I have created version 1.4.0 of the OpenAPI Validator, that makes it easier to return the validation details to the client. 

See the updated [README](https://github.com/Axway-API-Management-Plus/openapi-validator/blob/main/README.md#validate-request) which now includes that requirement.

When using for instance the `JSON Error` policy filter to handle this error the client will get the following HTTP 400 Response information:
```json
{
  "reasons": [
    {
      "language": "en",
      "message": "[ERROR - [Path '/id'] Instance type (string) does not match any allowed primitive type (allowed: [\"integer\"]): []]"
    }
  ],
  "details": {
    "msgId": "Id-297f41623d05114647150f11"
  }
}
```

**Comment by venkatesulua1990** [comment]
Thanks for making it , it really help our project
