### ISSUE TITLE
Problems with Content-Type

### ISSUE THREAD

**Issue by larswaldeZ** [Axway-API-Management-Plus/openapi-validator#7]
We get an error with a Request that has the Content-Type application/octet-stream

The API has the right configuration and is accepting "application/octet-stream".

But the Validator says the Content-Type is application/json

[Content_Type_Error.zip](https://github.com/Axway-API-Management-Plus/openapi-validator/files/8871147/Content_Type_Error.zip)

**Comment by cwiechmann** [comment]
Hi @larswaldeZ, Can you please for a moment enabled Log-Level DATA to see, if the following message is logged:

`Header: Content-Type not found. Defaulting to application/json.`

If yes, can you confirm the Header: `content-type` (case insensitive) is given?

FYI: I will change the log level of this message to DEBUG, as it makes more sense.

**Comment by larswaldeZ** [comment]
Hi Chris,
attached th Log as DATA
[3807a2628f8f67b7952b9648.txt](https://github.com/Axway-API-Management-Plus/openapi-validator/files/8871458/3807a2628f8f67b7952b9648.txt)
.
[received.txt](https://github.com/Axway-API-Management-Plus/openapi-validator/files/8871476/received.txt)

**Comment by cwiechmann** [comment]
I see the log message: `Header: Content-Type not found. Defaulting to application/json.`, which means the validator receives no content type header and defaults to application/json. 

In the code itself I left the following comment:

> // For any reason, sometimes the API-Gateway at runtime removes the Content-Type header from the attribute http.headers

I was able to reproduce the issue, as indeed the header Content-Type is missing in the attribute http.headers when accessed by custom policies. . 
I did some research, looking for a patch, toggle, etc. but no luck. 

Therefore I recommend to create a support case and ask, what to do about the missing Content-Type header in custom policies.

**Comment by cwiechmann** [comment]
Version 1.4.1 logs this message on DEBUG instead of DATA to make the problem more obvious.

**Comment by jpfaffenzeller** [comment]
Hi @cwiechmann 

Content-Type header is available in http.content.headers. 
I cannot find exactly when the change happened (I remember in old version headers were already separated between content headers and general headers), I just found a security fix about headers in May22, may be that's why content-type is not available anymore in http.headers (RDAPI-23779).
The easiest might be to look for headers values in http.headers and http.content.headers in the validator.

**Comment by cwiechmann** [comment]
Thanks @jpfaffenzeller for the hint. 

@larswaldeZ, please change the scripting filter in a way to merge the http.content.headers into https.headers. I have updated the example in the README:
![image](https://user-images.githubusercontent.com/16292002/173070111-1667625b-05bc-4d13-adbd-3688187fde41.png)
